# Generated by Django 5.1.3 on 2026-09-14 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_text', models.TextField()),
                ('is_start', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.TextField()),
                ('current_scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventure.story')),
                ('next_scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_choices', to='adventure.story')),
            ],
        ),
    ]
